name: ugly
run-name: Uglify some files
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
jobs:
  Uglify-Files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: 'scripts'
          output: 'dist'
      
      - uses: ActionwareIO/branch-push-action@action
        with:
          branch: final
          files: |
            index.html
            ./pages/**
            ./dist/**
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 'Minify action'
      #     branch: final