name: ugly
run-name: Uglify some files
on:
  push:
    branches:
      - dev
jobs:
  Uglify-Files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true
    
    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: final
